#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Laser

#include "Basic.hpp"

#include "B_Laser_classes.hpp"
#include "B_Laser_parameters.hpp"


namespace SDK
{

// Function B_Laser.B_Laser_C.ExecuteUbergraph_B_Laser
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Laser_C::ExecuteUbergraph_B_Laser(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Laser_C", "ExecuteUbergraph_B_Laser");

	Params::B_Laser_C_ExecuteUbergraph_B_Laser Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Laser.B_Laser_C.CE_Burst
// (BlueprintCallable, BlueprintEvent)

void AB_Laser_C::CE_Burst()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Laser_C", "CE_Burst");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Laser.B_Laser_C.BndEvt__P_ParticleUnit_K2Node_ComponentBoundEvent_0_OnSystemFinished__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UParticleSystemComponent*         PSystem                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Laser_C::BndEvt__P_ParticleUnit_K2Node_ComponentBoundEvent_0_OnSystemFinished__DelegateSignature(class UParticleSystemComponent* PSystem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Laser_C", "BndEvt__P_ParticleUnit_K2Node_ComponentBoundEvent_0_OnSystemFinished__DelegateSignature");

	Params::B_Laser_C_BndEvt__P_ParticleUnit_K2Node_ComponentBoundEvent_0_OnSystemFinished__DelegateSignature Parms{};

	Parms.PSystem = PSystem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Laser.B_Laser_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AB_Laser_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Laser_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

