#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Prj_Athena_SmokeBomb

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_Prj_Athena_Grenade_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Athena_SmokeBomb.B_Prj_Athena_SmokeBomb_C
// 0x0020 (0x07B0 - 0x0790)
class AB_Prj_Athena_SmokeBomb_C final : public AB_Prj_Athena_Grenade_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Prj_Athena_SmokeBomb_C;           // 0x0790(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x0798(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x07A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        P_SmokeGrenadeExplosion;                           // 0x07A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Prj_Athena_SmokeBomb(int32 EntryPoint);
	void FailsafeTimer();
	void ReceiveBeginPlay();
	void FuseEnded();
	void BndEvt__OverlapCapsule_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void OnExploded(const TArray<class AActor*>& HitActors, const TArray<struct FHitResult>& HitResults);
	void OnBounce(const struct FHitResult& Hit);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Prj_Athena_SmokeBomb_C">();
	}
	static class AB_Prj_Athena_SmokeBomb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Athena_SmokeBomb_C>();
	}
};

}

