#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FlyingVehicleBoundarySpline

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FlyingVehicleBoundarySpline.FlyingVehicleBoundarySpline_C
// 0x0010 (0x0250 - 0x0240)
class AFlyingVehicleBoundarySpline_C final : public AActor
{
public:
	class USplineComponent*                       Spline;                                            // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FlyingVehicleBoundarySpline_C">();
	}
	static class AFlyingVehicleBoundarySpline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingVehicleBoundarySpline_C>();
	}
};

}

