#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Frontend_Lobby_Season8_C

#include "Basic.hpp"

#include "Frontend_Lobby_Season8_C_classes.hpp"
#include "Frontend_Lobby_Season8_C_parameters.hpp"


namespace SDK
{

// Function Frontend_Lobby_Season8_C.Frontend_Lobby_Season8_C_C.ExecuteUbergraph_Frontend_Lobby_Season8_C
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFrontend_Lobby_Season8_C_C::ExecuteUbergraph_Frontend_Lobby_Season8_C(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Frontend_Lobby_Season8_C_C", "ExecuteUbergraph_Frontend_Lobby_Season8_C");

	Params::Frontend_Lobby_Season8_C_C_ExecuteUbergraph_Frontend_Lobby_Season8_C Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Frontend_Lobby_Season8_C.Frontend_Lobby_Season8_C_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AFrontend_Lobby_Season8_C_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Frontend_Lobby_Season8_C_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

