#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GAB_Melee_Blade_Combo_Athena

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "GAB_Melee_GenericCombo_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_Melee_Blade_Combo_Athena.GAB_Melee_Blade_Combo_Athena_C
// 0x00C8 (0x0A50 - 0x0988)
class UGAB_Melee_Blade_Combo_Athena_C final : public UGAB_Melee_GenericCombo_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GAB_Melee_Blade_Combo_Athena_C;     // 0x0988(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class AActor*>                         ActorsHitArray;                                    // 0x0990(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance)
	struct FFortGameplayAbilityMontageInfo        IcyMontage;                                        // 0x09A0(0x0058)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FFortGameplayAbilityMontageInfo        NormalMontage;                                     // 0x09F8(0x0058)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GAB_Melee_Blade_Combo_Athena(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void Added_2D57017544AB7D7ABF80BCA63BF72108();
	void Removed_395A74944908471AF9414B9609039D61();
	void Added_B70A00D24C2B1173FA78BCAD88A77F99();
	void ForceFeedbackOnhit(const struct FGameplayAbilityTargetDataHandle& TargetData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_Melee_Blade_Combo_Athena_C">();
	}
	static class UGAB_Melee_Blade_Combo_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_Melee_Blade_Combo_Athena_C>();
	}
};

}

