#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Activities_StWAntiShield_Inside

#include "Basic.hpp"

#include "GC_Activities_StWAntiShield_Inside_classes.hpp"
#include "GC_Activities_StWAntiShield_Inside_parameters.hpp"


namespace SDK
{

// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.ExecuteUbergraph_GC_Activities_StWAntiShield_Inside
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGC_Activities_StWAntiShield_Inside_C::ExecuteUbergraph_GC_Activities_StWAntiShield_Inside(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "ExecuteUbergraph_GC_Activities_StWAntiShield_Inside");

	Params::GC_Activities_StWAntiShield_Inside_C_ExecuteUbergraph_GC_Activities_StWAntiShield_Inside Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.FadeOut
// (BlueprintCallable, BlueprintEvent)

void AGC_Activities_StWAntiShield_Inside_C::FadeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "FadeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.FadeIn
// (BlueprintCallable, BlueprintEvent)

void AGC_Activities_StWAntiShield_Inside_C::FadeIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "FadeIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AGC_Activities_StWAntiShield_Inside_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.Fade Smoke TL__UpdateFunc
// (BlueprintEvent)

void AGC_Activities_StWAntiShield_Inside_C::Fade_Smoke_TL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "Fade Smoke TL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.Fade Smoke TL__FinishedFunc
// (BlueprintEvent)

void AGC_Activities_StWAntiShield_Inside_C::Fade_Smoke_TL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "Fade Smoke TL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AGC_Activities_StWAntiShield_Inside_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.OnActive
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AGC_Activities_StWAntiShield_Inside_C::OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "OnActive");

	Params::GC_Activities_StWAntiShield_Inside_C_OnActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GC_Activities_StWAntiShield_Inside.GC_Activities_StWAntiShield_Inside_C.OnRemove
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AGC_Activities_StWAntiShield_Inside_C::OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_Activities_StWAntiShield_Inside_C", "OnRemove");

	Params::GC_Activities_StWAntiShield_Inside_C_OnRemove Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

