#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_Loop_Goose_SLOW

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Loop_Goose_SLOW.GCN_Loop_Goose_SLOW_C
// 0x0000 (0x0790 - 0x0790)
class AGCN_Loop_Goose_SLOW_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_Loop_Goose_SLOW_C">();
	}
	static class AGCN_Loop_Goose_SLOW_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_Loop_Goose_SLOW_C>();
	}
};

}

