#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCNL_Creative_BarrelExplosion_Player

#include "Basic.hpp"

#include "GCNL_Creative_BarrelExplosion_Player_classes.hpp"
#include "GCNL_Creative_BarrelExplosion_Player_parameters.hpp"


namespace SDK
{

// Function GCNL_Creative_BarrelExplosion_Player.GCNL_Creative_BarrelExplosion_Player_C.ExecuteUbergraph_GCNL_Creative_BarrelExplosion_Player
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGCNL_Creative_BarrelExplosion_Player_C::ExecuteUbergraph_GCNL_Creative_BarrelExplosion_Player(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCNL_Creative_BarrelExplosion_Player_C", "ExecuteUbergraph_GCNL_Creative_BarrelExplosion_Player");

	Params::GCNL_Creative_BarrelExplosion_Player_C_ExecuteUbergraph_GCNL_Creative_BarrelExplosion_Player Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GCNL_Creative_BarrelExplosion_Player.GCNL_Creative_BarrelExplosion_Player_C.OnApplication
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const TArray<class UParticleSystemComponent*>&ParticleComponents                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
// const TArray<class UAudioComponent*>&   AudioComponents                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
// class UCameraShake*                     BurstCameraShakeInstance                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ADecalActor*                      BurstDecalInstance                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGCNL_Creative_BarrelExplosion_Player_C::OnApplication(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCNL_Creative_BarrelExplosion_Player_C", "OnApplication");

	Params::GCNL_Creative_BarrelExplosion_Player_C_OnApplication Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);
	Parms.ParticleComponents = std::move(ParticleComponents);
	Parms.AudioComponents = std::move(AudioComponents);
	Parms.BurstCameraShakeInstance = BurstCameraShakeInstance;
	Parms.BurstDecalInstance = BurstDecalInstance;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GCNL_Creative_BarrelExplosion_Player.GCNL_Creative_BarrelExplosion_Player_C.PPTL__FinishedFunc
// (BlueprintEvent)

void AGCNL_Creative_BarrelExplosion_Player_C::PPTL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCNL_Creative_BarrelExplosion_Player_C", "PPTL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GCNL_Creative_BarrelExplosion_Player.GCNL_Creative_BarrelExplosion_Player_C.PPTL__UpdateFunc
// (BlueprintEvent)

void AGCNL_Creative_BarrelExplosion_Player_C::PPTL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GCNL_Creative_BarrelExplosion_Player_C", "PPTL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

