#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SquadSelection

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SquadSelection.SquadSelection_C
// 0x0008 (0x03B8 - 0x03B0)
class USquadSelection_C final : public UFortSquadSelectionMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SquadSelection(int32 EntryPoint);
	void OnLocalPlayerParticipationChanged(bool bIsParticipating);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SquadSelection_C">();
	}
	static class USquadSelection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USquadSelection_C>();
	}
};

}

